In [12]:
import pandas
from datetime import datetime
from pytz import utc

In [19]:
data = pandas.read_csv("reviews.csv" , parse_dates=["Timestamp"])

In [14]:
data

,Course Name,Timestamp,Rating,Comment
0,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 06:25:52+00:00,4.0,NaN
1,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:12:34+00:00,4.0,NaN
2,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 05:11:03+00:00,4.0,NaN
3,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:33:24+00:00,5.0,NaN
4,The Python Mega Course: Build 10 Real World Ap...,2021-04-02 03:31:49+00:00,4.5,NaN
...,...,...,...,...
44995,Python for Beginners with Examples,2018-01-01 01:11:26+00:00,4.0,NaN
44996,The Python Mega Course: Build 10 Real World Ap...,2018-01-01 01:09:56+00:00,5.0,NaN
44997,The Python Mega Course: Build 10 Real World Ap...,2018-01-01 01:08:11+00:00,5.0,NaN
44998,Python for Beginners with Examples,2018-01-01 01:05:26+00:00,5.0,NaN
44999,The Python Mega Course: Build 10 Real World Ap...,2018-01-01 01:01:16+00:00,5.0,NaN

In [20]:
data[(data['Timestamp'] >= datetime(2020, 5, 1, tzinfo=utc)) & ( data['Timestamp'] <= datetime(2021, 3, 2, tzinfo=utc))]

,Course Name,Timestamp,Rating,Comment
908,The Complete Python Course: Build 10 Professio...,2021-03-01 23:05:29+00:00,5.0,NaN
909,The Python Mega Course: Build 10 Real World Ap...,2021-03-01 22:37:45+00:00,5.0,NaN
910,The Python Mega Course: Build 10 Real World Ap...,2021-03-01 22:02:51+00:00,5.0,NaN
911,The Complete Python Course: Build 10 Professio...,2021-03-01 21:56:23+00:00,2.5,NaN
912,The Python Mega Course: Build 10 Real World Ap...,2021-03-01 20:39:06+00:00,5.0,NaN
...,...,...,...,...
13496,The Python Mega Course: Build 10 Real World Ap...,2020-05-01 02:54:09+00:00,4.5,NaN
13497,Data Processing with Python,2020-05-01 02:19:13+00:00,4.0,NaN
13498,The Python Mega Course: Build 10 Real World Ap...,2020-05-01 01:33:01+00:00,5.0,NaN
13499,The Python Mega Course: Build 10 Real World Ap...,2020-05-01 01:19:37+00:00,3.5,NaN
13500,The Python Mega Course: Build 10 Real World Ap...,2020-05-01 00:13:37+00:00,4.0,NaN